### ISSUE TITLE
Mismatch between status bar color and selected page color

### ISSUE THREAD

**Issue by Zhuinden** [xzhorikx/slider-intro#1]
![image](https://user-images.githubusercontent.com/11718392/81825468-ff2af780-9536-11ea-8df1-4c0c0b2fd028.png)

**Comment by xzhorikx** [comment]
This was intended but a good spot overall. Will try to make it the same color as a current background

**Comment by xzhorikx** [comment]
Implemented in https://github.com/xzhorikx/slider-intro/commit/ff497482260920b4a2a957d39ab3680fa3def06c, thank you for your suggestion

![](https://github.com/xzhorikx/slider-intro/blob/master/intro.gif)
